# cards.py
tarot_cards = [
    # Major Arcana / Старшие Арканы
    {"name": {"en": "The Fool", "ru": "Шут"}, "meaning": {"en": "New beginnings, adventures, freedom.", "ru": "Новые начинания, приключения, свобода."}, "image": "images/major_arcana_fool_thumb.jpg"},
    {"name": {"en": "The Magician", "ru": "Маг"}, "meaning": {"en": "Creativity, resourcefulness, power.", "ru": "Творчество, изобретательность, сила."}, "image": "images/major_arcana_magician_thumb.jpg"},
    {"name": {"en": "The High Priestess", "ru": "Верховная Жрица"}, "meaning": {"en": "Intuition, mystery, subconscious.", "ru": "Интуиция, тайна, подсознание."}, "image": "images/major_arcana_priestess_thumb.jpg"},
    {"name": {"en": "The Empress", "ru": "Императрица"}, "meaning": {"en": "Fertility, abundance, nurturing.", "ru": "Плодородие, изобилие, забота."}, "image": "images/major_arcana_empress_thumb.jpg"},
    {"name": {"en": "The Emperor", "ru": "Император"}, "meaning": {"en": "Authority, structure, stability.", "ru": "Власть, структура, стабильность."}, "image": "images/major_arcana_emperor_thumb.jpg"},
    {"name": {"en": "The Hierophant", "ru": "Иерофант"}, "meaning": {"en": "Tradition, spiritual guidance, learning.", "ru": "Традиция, духовное руководство, обучение."}, "image": "images/major_arcana_hierophant_thumb.jpg"},
    {"name": {"en": "The Lovers", "ru": "Влюбленные"}, "meaning": {"en": "Love, harmony, choices.", "ru": "Любовь, гармония, выбор."}, "image": "images/major_arcana_lovers_thumb.jpg"},
    {"name": {"en": "The Chariot", "ru": "Колесница"}, "meaning": {"en": "Control, determination, willpower.", "ru": "Контроль, решительность, сила воли."}, "image": "images/major_arcana_chariot_thumb.jpg"},
    {"name": {"en": "Strength", "ru": "Сила"}, "meaning": {"en": "Courage, patience, inner strength.", "ru": "Мужество, терпение, внутренняя сила."}, "image": "images/major_arcana_strength_thumb.jpg"},
    {"name": {"en": "The Hermit", "ru": "Отшельник"}, "meaning": {"en": "Introspection, solitude, guidance.", "ru": "Самоанализ, уединение, руководство."}, "image": "images/major_arcana_hermit_thumb.jpg"},
    {"name": {"en": "Wheel of Fortune", "ru": "Колесо Фортуны"}, "meaning": {"en": "Cycles, destiny, change.", "ru": "Циклы, судьба, перемены."}, "image": "images/major_arcana_fortune_thumb.jpg"},
    {"name": {"en": "Justice", "ru": "Правосудие"}, "meaning": {"en": "Fairness, truth, law.", "ru": "Справедливость, истина, закон."}, "image": "images/major_arcana_justice_thumb.jpg"},
    {"name": {"en": "The Hanged Man", "ru": "Повешенный"}, "meaning": {"en": "Pause, surrender, perspective.", "ru": "Пауза, сдача, перспектива."}, "image": "images/major_arcana_hanged_thumb.jpg"},
    {"name": {"en": "Death", "ru": "Смерть"}, "meaning": {"en": "Transformation, endings, new beginnings.", "ru": "Трансформация, окончания, новые начала."}, "image": "images/major_arcana_death_thumb.jpg"},
    {"name": {"en": "Temperance", "ru": "Умеренность"}, "meaning": {"en": "Balance, patience, moderation.", "ru": "Баланс, терпение, умеренность."}, "image": "images/major_arcana_temperance_thumb.jpg"},
    {"name": {"en": "The Devil", "ru": "Дьявол"}, "meaning": {"en": "Addiction, materialism, shadow self.", "ru": "Зависимость, материализм, теневая сторона."}, "image": "images/major_arcana_devil_thumb.jpg"},
    {"name": {"en": "The Tower", "ru": "Башня"}, "meaning": {"en": "Sudden change, upheaval, revelation.", "ru": "Внезапные перемены, потрясения, откровения."}, "image": "images/major_arcana_tower_thumb.jpg"},
    {"name": {"en": "The Star", "ru": "Звезда"}, "meaning": {"en": "Hope, inspiration, serenity.", "ru": "Надежда, вдохновение, безмятежность."}, "image": "images/major_arcana_star_thumb.jpg"},
    {"name": {"en": "The Moon", "ru": "Луна"}, "meaning": {"en": "Illusion, intuition, fear.", "ru": "Иллюзия, интуиция, страх."}, "image": "images/major_arcana_moon_thumb.jpg"},
    {"name": {"en": "The Sun", "ru": "Солнце"}, "meaning": {"en": "Joy, success, vitality.", "ru": "Радость, успех, жизненная сила."}, "image": "images/major_arcana_sun_thumb.jpg"},
    {"name": {"en": "Judgement", "ru": "Суд"}, "meaning": {"en": "Reflection, reckoning, awakening.", "ru": "Размышление, расплата, пробуждение."}, "image": "images/major_arcana_judgement_thumb.jpg"},
    {"name": {"en": "The World", "ru": "Мир"}, "meaning": {"en": "Completion, accomplishment, travel.", "ru": "Завершение, достижение, путешествия."}, "image": "images/major_arcana_world_thumb.jpg"},

    # Cups / Кубки
    {"name": {"en": "Ace of Cups", "ru": "Туз Кубков"}, "meaning": {"en": "New feelings, romance, compassion.", "ru": "Новые чувства, романтика, сострадание."}, "image": "images/minor_arcana_cups_ace_thumb.jpg"},
    {"name": {"en": "Two of Cups", "ru": "Двойка Кубков"}, "meaning": {"en": "Partnership, love, connection.", "ru": "Партнерство, любовь, связь."}, "image": "images/minor_arcana_cups_2_thumb.jpg"},
    {"name": {"en": "Three of Cups", "ru": "Тройка Кубков"}, "meaning": {"en": "Celebration, friendship, creativity.", "ru": "Празднование, дружба, творчество."}, "image": "images/minor_arcana_cups_3_thumb.jpg"},
    {"name": {"en": "Four of Cups", "ru": "Четверка Кубков"}, "meaning": {"en": "Apathy, contemplation, reevaluation.", "ru": "Апатия, созерцание, переоценка."}, "image": "images/minor_arcana_cups_4_thumb.jpg"},
    {"name": {"en": "Five of Cups", "ru": "Пятерка Кубков"}, "meaning": {"en": "Loss, regret, disappointment.", "ru": "Потеря, сожаление, разочарование."}, "image": "images/minor_arcana_cups_5_thumb.jpg"},
    {"name": {"en": "Six of Cups", "ru": "Шестерка Кубков"}, "meaning": {"en": "Nostalgia, reunion, innocence.", "ru": "Ностальгия, воссоединение, невинность."}, "image": "images/minor_arcana_cups_6_thumb.jpg"},
    {"name": {"en": "Seven of Cups", "ru": "Семерка Кубков"}, "meaning": {"en": "Choices, fantasy, illusion.", "ru": "Выбор, фантазия, иллюзия."}, "image": "images/minor_arcana_cups_7_thumb.jpg"},
    {"name": {"en": "Eight of Cups", "ru": "Восьмерка Кубков"}, "meaning": {"en": "Walking away, introspection.", "ru": "Уход, самоанализ."}, "image": "images/minor_arcana_cups_8_thumb.jpg"},
    {"name": {"en": "Nine of Cups", "ru": "Девятка Кубков"}, "meaning": {"en": "Contentment, satisfaction, wish fulfillment.", "ru": "Довольство, удовлетворение, исполнение желаний."}, "image": "images/minor_arcana_cups_9_thumb.jpg"},
    {"name": {"en": "Ten of Cups", "ru": "Десятка Кубков"}, "meaning": {"en": "Happiness, family, harmony.", "ru": "Счастье, семья, гармония."}, "image": "images/minor_arcana_cups_10_thumb.jpg"},
    {"name": {"en": "Page of Cups", "ru": "Паж Кубков"}, "meaning": {"en": "Imagination, sensitivity, curiosity.", "ru": "Воображение, чувствительность, любопытство."}, "image": "images/minor_arcana_cups_page_thumb.jpg"},
    {"name": {"en": "Knight of Cups", "ru": "Рыцарь Кубков"}, "meaning": {"en": "Romance, charm, adventure.", "ru": "Романтика, обаяние, приключение."}, "image": "images/minor_arcana_cups_knight_thumb.jpg"},
    {"name": {"en": "Queen of Cups", "ru": "Королева Кубков"}, "meaning": {"en": "Compassion, calm, intuition.", "ru": "Сострадание, спокойствие, интуиция."}, "image": "images/minor_arcana_cups_queen_thumb.jpg"},
    {"name": {"en": "King of Cups", "ru": "Король Кубков"}, "meaning": {"en": "Wisdom, diplomacy, emotional balance.", "ru": "Мудрость, дипломатия, эмоциональный баланс."}, "image": "images/minor_arcana_cups_king_thumb.jpg"},

    # Wands / Жезлы
    {"name": {"en": "Ace of Wands", "ru": "Туз Жезлов"}, "meaning": {"en": "New opportunities, growth, inspiration.", "ru": "Новые возможности, рост, вдохновение."}, "image": "images/minor_arcana_wands_ace_thumb.jpg"},
    {"name": {"en": "Two of Wands", "ru": "Двойка Жезлов"}, "meaning": {"en": "Planning, progress, decisions.", "ru": "Планирование, прогресс, решения."}, "image": "images/minor_arcana_wands_2_thumb.jpg"},
    {"name": {"en": "Three of Wands", "ru": "Тройка Жезлов"}, "meaning": {"en": "Expansion, foresight, growth.", "ru": "Расширение, предвидение, рост."}, "image": "images/minor_arcana_wands_3_thumb.jpg"},
    {"name": {"en": "Four of Wands", "ru": "Четверка Жезлов"}, "meaning": {"en": "Celebration, harmony, home.", "ru": "Празднование, гармония, дом."}, "image": "images/minor_arcana_wands_4_thumb.jpg"},
    {"name": {"en": "Five of Wands", "ru": "Пятерка Жезлов"}, "meaning": {"en": "Conflict, competition, challenges.", "ru": "Конфликт, конкуренция, вызовы."}, "image": "images/minor_arcana_wands_5_thumb.jpg"},
    {"name": {"en": "Six of Wands", "ru": "Шестерка Жезлов"}, "meaning": {"en": "Victory, recognition, success.", "ru": "Победа, признание, успех."}, "image": "images/minor_arcana_wands_6_thumb.jpg"},
    {"name": {"en": "Seven of Wands", "ru": "Семерка Жезлов"}, "meaning": {"en": "Defense, perseverance, challenge.", "ru": "Защита, настойчивость, вызов."}, "image": "images/minor_arcana_wands_7_thumb.jpg"},
    {"name": {"en": "Eight of Wands", "ru": "Восьмерка Жезлов"}, "meaning": {"en": "Movement, action, speed.", "ru": "Движение, действие, скорость."}, "image": "images/minor_arcana_wands_8_thumb.jpg"},
    {"name": {"en": "Nine of Wands", "ru": "Девятка Жезлов"}, "meaning": {"en": "Resilience, persistence, stamina.", "ru": "Устойчивость, настойчивость, выносливость."}, "image": "images/minor_arcana_wands_9_thumb.jpg"},
    {"name": {"en": "Ten of Wands", "ru": "Десятка Жезлов"}, "meaning": {"en": "Burden, responsibility, hard work.", "ru": "Бремя, ответственность, тяжелая работа."}, "image": "images/minor_arcana_wands_10_thumb.jpg"},
    {"name": {"en": "Page of Wands", "ru": "Паж Жезлов"}, "meaning": {"en": "Exploration, enthusiasm, discovery.", "ru": "Исследование, энтузиазм, открытие."}, "image": "images/minor_arcana_wands_page_thumb.jpg"},
    {"name": {"en": "Knight of Wands", "ru": "Рыцарь Жезлов"}, "meaning": {"en": "Energy, adventure, impulsiveness.", "ru": "Энергия, приключение, импульсивность."}, "image": "images/minor_arcana_wands_knight_thumb.jpg"},
    {"name": {"en": "Queen of Wands", "ru": "Королева Жезлов"}, "meaning": {"en": "Confidence, determination, warmth.", "ru": "Уверенность, решительность, теплота."}, "image": "images/minor_arcana_wands_queen_thumb.jpg"},
    {"name": {"en": "King of Wands", "ru": "Король Жезлов"}, "meaning": {"en": "Leadership, vision, entrepreneurship.", "ru": "Лидерство, видение, предпринимательство."}, "image": "images/minor_arcana_wands_king_thumb.jpg"},

    # Swords / Мечи
    {"name": {"en": "Ace of Swords", "ru": "Туз Мечей"}, "meaning": {"en": "Clarity, new ideas, breakthroughs.", "ru": "Ясность, новые идеи, прорывы."}, "image": "images/minor_arcana_swords_ace_thumb.jpg"},
    {"name": {"en": "Two of Swords", "ru": "Двойка Мечей"}, "meaning": {"en": "Dilemma, choices, indecision.", "ru": "Дилемма, выбор, нерешительность."}, "image": "images/minor_arcana_swords_2_thumb.jpg"},
    {"name": {"en": "Three of Swords", "ru": "Тройка Мечей"}, "meaning": {"en": "Heartbreak, grief, emotional pain.", "ru": "Разбитое сердце, горе, эмоциональная боль."}, "image": "images/minor_arcana_swords_3_thumb.jpg"},
    {"name": {"en": "Four of Swords", "ru": "Четверка Мечей"}, "meaning": {"en": "Rest, recovery, contemplation.", "ru": "Отдых, восстановление, созерцание."}, "image": "images/minor_arcana_swords_4_thumb.jpg"},
    {"name": {"en": "Five of Swords", "ru": "Пятерка Мечей"}, "meaning": {"en": "Conflict, tension, loss.", "ru": "Конфликт, напряжение, потеря."}, "image": "images/minor_arcana_swords_5_thumb.jpg"},
    {"name": {"en": "Six of Swords", "ru": "Шестерка Мечей"}, "meaning": {"en": "Transition, change, journey.", "ru": "Переход, изменение, путешествие."}, "image": "images/minor_arcana_swords_6_thumb.jpg"},
    {"name": {"en": "Seven of Swords", "ru": "Семерка Мечей"}, "meaning": {"en": "Deception, strategy, stealth.", "ru": "Обман, стратегия, скрытность."}, "image": "images/minor_arcana_swords_7_thumb.jpg"},
        {"name": {"en": "Eight of Swords", "ru": "Восьмерка Мечей"}, "meaning": {"en": "Restriction, limitation, fear.", "ru": "Ограничение, ограничения, страх."}, "image": "images/minor_arcana_swords_8_thumb.jpg"},
    {"name": {"en": "Nine of Swords", "ru": "Девятка Мечей"}, "meaning": {"en": "Anxiety, worry, nightmares.", "ru": "Тревога, беспокойство, кошмары."}, "image": "images/minor_arcana_swords_9_thumb.jpg"},
    {"name": {"en": "Ten of Swords", "ru": "Десятка Мечей"}, "meaning": {"en": "Betrayal, endings, loss.", "ru": "Предательство, окончания, потеря."}, "image": "images/minor_arcana_swords_10_thumb.jpg"},
    {"name": {"en": "Page of Swords", "ru": "Паж Мечей"}, "meaning": {"en": "Curiosity, vigilance, communication.", "ru": "Любопытство, бдительность, общение."}, "image": "images/minor_arcana_swords_page_thumb.jpg"},
    {"name": {"en": "Knight of Swords", "ru": "Рыцарь Мечей"}, "meaning": {"en": "Action, impulsiveness, intellect.", "ru": "Действие, импульсивность, интеллект."}, "image": "images/minor_arcana_swords_knight_thumb.jpg"},
    {"name": {"en": "Queen of Swords", "ru": "Королева Мечей"}, "meaning": {"en": "Perception, independence, clarity.", "ru": "Восприятие, независимость, ясность."}, "image": "images/minor_arcana_swords_queen_thumb.jpg"},
    {"name": {"en": "King of Swords", "ru": "Король Мечей"}, "meaning": {"en": "Authority, truth, analytical thinking.", "ru": "Власть, истина, аналитическое мышление."}, "image": "images/minor_arcana_swords_king_thumb.jpg"},

    # Pentacles / Пентакли
    {"name": {"en": "Ace of Pentacles", "ru": "Туз Пентаклей"}, "meaning": {"en": "New financial opportunity, prosperity.", "ru": "Новая финансовая возможность, процветание."}, "image": "images/minor_arcana_pentacles_ace_thumb.jpg"},
    {"name": {"en": "Two of Pentacles", "ru": "Двойка Пентаклей"}, "meaning": {"en": "Balance, adaptability, multitasking.", "ru": "Баланс, адаптивность, многозадачность."}, "image": "images/minor_arcana_pentacles_2_thumb.jpg"},
    {"name": {"en": "Three of Pentacles", "ru": "Тройка Пентаклей"}, "meaning": {"en": "Collaboration, skill, teamwork.", "ru": "Сотрудничество, мастерство, командная работа."}, "image": "images/minor_arcana_pentacles_3_thumb.jpg"},
    {"name": {"en": "Four of Pentacles", "ru": "Четверка Пентаклей"}, "meaning": {"en": "Control, stability, possession.", "ru": "Контроль, стабильность, владение."}, "image": "images/minor_arcana_pentacles_4_thumb.jpg"},
    {"name": {"en": "Five of Pentacles", "ru": "Пятерка Пентаклей"}, "meaning": {"en": "Loss, insecurity, hardship.", "ru": "Потеря, неуверенность, трудности."}, "image": "images/minor_arcana_pentacles_5_thumb.jpg"},
    {"name": {"en": "Six of Pentacles", "ru": "Шестерка Пентаклей"}, "meaning": {"en": "Generosity, charity, sharing.", "ru": "Щедрость, благотворительность, делиться."}, "image": "images/minor_arcana_pentacles_6_thumb.jpg"},
    {"name": {"en": "Seven of Pentacles", "ru": "Семерка Пентаклей"}, "meaning": {"en": "Patience, planning, assessment.", "ru": "Терпение, планирование, оценка."}, "image": "images/minor_arcana_pentacles_7_thumb.jpg"},
    {"name": {"en": "Eight of Pentacles", "ru": "Восьмерка Пентаклей"}, "meaning": {"en": "Skill, mastery, diligence.", "ru": "Мастерство, совершенство, усердие."}, "image": "images/minor_arcana_pentacles_8_thumb.jpg"},
    {"name": {"en": "Nine of Pentacles", "ru": "Девятка Пентаклей"}, "meaning": {"en": "Self-sufficiency, luxury, success.", "ru": "Самостоятельность, роскошь, успех."}, "image": "images/minor_arcana_pentacles_9_thumb.jpg"},
    {"name": {"en": "Ten of Pentacles", "ru": "Десятка Пентаклей"}, "meaning": {"en": "Wealth, family legacy, stability.", "ru": "Богатство, семейное наследие, стабильность."}, "image": "images/minor_arcana_pentacles_10_thumb.jpg"},
    {"name": {"en": "Page of Pentacles", "ru": "Паж Пентаклей"}, "meaning": {"en": "Learning, opportunity, ambition.", "ru": "Обучение, возможность, амбиции."}, "image": "images/minor_arcana_pentacles_page_thumb.jpg"},
    {"name": {"en": "Knight of Pentacles", "ru": "Рыцарь Пентаклей"}, "meaning": {"en": "Hard work, responsibility, routine.", "ru": "Тяжелая работа, ответственность, рутина."}, "image": "images/minor_arcana_pentacles_knight_thumb.jpg"},
    {"name": {"en": "Queen of Pentacles", "ru": "Королева Пентаклей"}, "meaning": {"en": "Nurturing, practicality, financial stability.", "ru": "Забота, практичность, финансовая стабильность."}, "image": "images/minor_arcana_pentacles_queen_thumb.jpg"},
    {"name": {"en": "King of Pentacles", "ru": "Король Пентаклей"}, "meaning": {"en": "Wealth, leadership, discipline.", "ru": "Богатство, лидерство, дисциплина."}, "image": "images/minor_arcana_pentacles_king_thumb.jpg"}
]